### ISSUE TITLE
Folder Permissions Issue when Uploading Media

### ISSUE THREAD

**Issue by loopy3025** [docksal/drupal7#8]
We have an issue when running docksal on Windows. When trying to upload a file, we get a permissions error. This does not make a lot of sense because the folders all have the correct permissions. Please see the screenshots for all the details.

![captureahl](https://user-images.githubusercontent.com/6729935/37419654-55fdf7fe-278b-11e8-8f5f-7ddf291d2cc4.PNG)
![capturefatureimage](https://user-images.githubusercontent.com/6729935/37419655-560b9ac6-278b-11e8-8054-ed8bfff38ebf.PNG)
![captureerror](https://user-images.githubusercontent.com/6729935/37419656-561a2258-278b-11e8-93de-6374d9f3f700.PNG)
![capturefolderpermissions](https://user-images.githubusercontent.com/6729935/37419657-5626c206-278b-11e8-89a6-461c73e324f3.PNG)

**Comment by achekulaev** [comment]
1. Make sure the dir is writeable `fin exec touch docroot/sites/default/files/12345` 
2. Make sure that `public://` is configured properly in Drupal 
3. Make sure `tmp` is configured properly in Drupal

```php
# File system settings.
$conf['file_temporary_path'] = '/tmp';
# Workaround for permission issues with NFS shares
$conf['file_chmod_directory'] = 0777;
$conf['file_chmod_file'] = 0666;
```

**Comment by loopy3025** [comment]
I have gone through all that, but I will quadruple check and provide screenshots. Tomorrow. 

As a side note, I set it up on my mac today and I'm having the same problem.

**Comment by achekulaev** [comment]
THe fact that you experience the issue on Mac as well speaks in favor of error in site configuration, rather that some DevOps issue.

**Comment by loopy3025** [comment]
Thanks again for always responding to us @achekulaev . We really appreciate it.

I ran through the list and here's the results...

1) Tested the permissions by deleting a file from the virtual environment on the command line...
![1-check](https://user-images.githubusercontent.com/6729935/37518484-b5c7d7c0-28eb-11e8-823a-1f39adf619de.PNG)

2) Checked the settings.local.php
![2-settings](https://user-images.githubusercontent.com/6729935/37518487-b7a18c62-28eb-11e8-8f0c-b017675d7bce.png)

3) Checked to make sure they're reflected in the system...
![3-gui](https://user-images.githubusercontent.com/6729935/37518489-b8bfed8c-28eb-11e8-989f-f11f76505b9e.PNG)

4) Tested the upload...
![4-error-in-gui](https://user-images.githubusercontent.com/6729935/37518491-b9c2411c-28eb-11e8-8264-84dfb36cb62c.PNG)

5) Looked at the watchdog error...
![5-watchdog](https://user-images.githubusercontent.com/6729935/37518492-baa6537a-28eb-11e8-8e87-5511f0977c08.PNG)

Is there any more information I can help provide?

**Comment by achekulaev** [comment]
Show `fin config` please

**Comment by loopy3025** [comment]
Sure thing. Thanks again for your help, Oleksii.
```
COMPOSE_PROJECT_NAME_SAFE: opwdd
COMPOSE_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/volumes-bind.yml
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/.docksal/stacks/stack-default.yml
ENV_FILE:
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/opwdd/.docksal/docksal.env
C:/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/opwdd/.docksal/docksal-local.env

PROJECT_ROOT: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/opwdd
DOCROOT: docroot
VIRTUAL_HOST: opwdd.docksal
VIRTUAL_HOST_ALIASES: *.opwdd.docksal
IP: 192.168.64.100
MYSQL: 192.168.64.100:32774

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      DOCROOT: docroot
      HOST_GID: null
      HOST_UID: null
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:1.3-php5
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - /home/docker
    - project_root:/var/www:rw,nocopy
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/db:1.1-mysql-5.6
    ports:
    - 0:3306/tcp
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
    hostname: web
    image: docksal/web:2.1-apache2.4
    labels:
      io.docksal.project-root: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/opwdd
      io.docksal.virtual-host: opwdd.docksal,*.opwdd.docksal
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /c/Users/afasoldt/.babun/cygwin/home/afasoldt/projects/opwdd
      o: bind
      type: none

---------------------
```
